-- Focustime — team enquiries from the landing page form.
-- Run once in the Supabase SQL editor. Safe to re-run.
--
-- The older `contact_submissions` table stays as-is: it now only holds partner
-- enquiries from /partners.html. The website falls back to it if this table is
-- missing, so nothing is lost if this script has not been run yet.

CREATE TABLE IF NOT EXISTS public.team_enquiries (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name        TEXT NOT NULL,
  email       TEXT NOT NULL,
  company     TEXT NOT NULL,
  team_size   TEXT NOT NULL,
  topic       TEXT NOT NULL,
  timing      TEXT,
  -- Sales workflow columns, for you rather than the website.
  contacted   BOOLEAN NOT NULL DEFAULT FALSE,
  notes       TEXT
);

COMMENT ON TABLE public.team_enquiries IS
  'Enquiries from software teams who want to book a focus week.';

CREATE INDEX IF NOT EXISTS idx_team_enquiries_created_at
  ON public.team_enquiries (created_at DESC);

ALTER TABLE public.team_enquiries ENABLE ROW LEVEL SECURITY;

-- Anyone can submit the form; only you can read what came in.
DROP POLICY IF EXISTS "Allow anonymous inserts" ON public.team_enquiries;
CREATE POLICY "Allow anonymous inserts" ON public.team_enquiries
  FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated reads" ON public.team_enquiries;
CREATE POLICY "Allow authenticated reads" ON public.team_enquiries
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow authenticated updates" ON public.team_enquiries;
CREATE POLICY "Allow authenticated updates" ON public.team_enquiries
  FOR UPDATE TO authenticated USING (true);

-- After running this, add a Database Webhook (Database → Webhooks) on INSERT
-- to public.team_enquiries pointing at:
--   https://<project-ref>.supabase.co/functions/v1/send-form-notification
-- The same edge function already handles partner enquiries.
